//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novo.Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressType
    {
        public AddressType()
        {
            this.MedicalProviderAddresses = new HashSet<MedicalProviderAddress>();
            this.PatientAddresses = new HashSet<PatientAddress>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<MedicalProviderAddress> MedicalProviderAddresses { get; set; }
        public virtual ICollection<PatientAddress> PatientAddresses { get; set; }
    }
}
