//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novo.Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalProviderMedicalFacility
    {
        public int Id { get; set; }
        public int MedicalProviderId { get; set; }
        public int MedicalFacilityId { get; set; }
        public int JobRoleId { get; set; }
    
        public virtual JobRole JobRole { get; set; }
        public virtual MedicalFacility MedicalFacility { get; set; }
        public virtual MedicalProvider MedicalProvider { get; set; }
    }
}
