//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novo.Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalFacility
    {
        public MedicalFacility()
        {
            this.MedicalProviderMedicalFacilities = new HashSet<MedicalProviderMedicalFacility>();
            this.Visits = new HashSet<Visit>();
            this.Visits1 = new HashSet<Visit>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string WebUrl { get; set; }
    
        public virtual ICollection<MedicalProviderMedicalFacility> MedicalProviderMedicalFacilities { get; set; }
        public virtual ICollection<Visit> Visits { get; set; }
        public virtual ICollection<Visit> Visits1 { get; set; }
    }
}
