//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novo.Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalProvider
    {
        public MedicalProvider()
        {
            this.MedicalProviderAddresses = new HashSet<MedicalProviderAddress>();
            this.MedicalProviderEmails = new HashSet<MedicalProviderEmail>();
            this.MedicalProviderMedicalFacilities = new HashSet<MedicalProviderMedicalFacility>();
            this.MedicalProviderPhones = new HashSet<MedicalProviderPhone>();
            this.Patients = new HashSet<Patient>();
            this.Visits = new HashSet<Visit>();
            this.Visits1 = new HashSet<Visit>();
        }
    
        public int Id { get; set; }
        public int MedicalProviderTypeId { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public int GenderId { get; set; }
        public string WebUrl { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual MedicalProviderType MedicalProviderType { get; set; }
        public virtual ICollection<MedicalProviderAddress> MedicalProviderAddresses { get; set; }
        public virtual ICollection<MedicalProviderEmail> MedicalProviderEmails { get; set; }
        public virtual ICollection<MedicalProviderMedicalFacility> MedicalProviderMedicalFacilities { get; set; }
        public virtual ICollection<MedicalProviderPhone> MedicalProviderPhones { get; set; }
        public virtual ICollection<Patient> Patients { get; set; }
        public virtual ICollection<Visit> Visits { get; set; }
        public virtual ICollection<Visit> Visits1 { get; set; }
    }
}
