//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novo.Web.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddressType> AddressTypes { get; set; }
        public virtual DbSet<Allergy> Allergies { get; set; }
        public virtual DbSet<DosageUnitType> DosageUnitTypes { get; set; }
        public virtual DbSet<EmailType> EmailTypes { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Investigation> Investigations { get; set; }
        public virtual DbSet<JobRole> JobRoles { get; set; }
        public virtual DbSet<MaritialStatu> MaritialStatus { get; set; }
        public virtual DbSet<MedicalFacility> MedicalFacilities { get; set; }
        public virtual DbSet<MedicalProvider> MedicalProviders { get; set; }
        public virtual DbSet<MedicalProviderAddress> MedicalProviderAddresses { get; set; }
        public virtual DbSet<MedicalProviderEmail> MedicalProviderEmails { get; set; }
        public virtual DbSet<MedicalProviderMedicalFacility> MedicalProviderMedicalFacilities { get; set; }
        public virtual DbSet<MedicalProviderPhone> MedicalProviderPhones { get; set; }
        public virtual DbSet<MedicalProviderType> MedicalProviderTypes { get; set; }
        public virtual DbSet<Medication> Medications { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<PatientAddress> PatientAddresses { get; set; }
        public virtual DbSet<PatientAllergy> PatientAllergies { get; set; }
        public virtual DbSet<PatientEmail> PatientEmails { get; set; }
        public virtual DbSet<PatientMedication> PatientMedications { get; set; }
        public virtual DbSet<PatientNote> PatientNotes { get; set; }
        public virtual DbSet<PatientPersonIdentifier> PatientPersonIdentifiers { get; set; }
        public virtual DbSet<PatientPhone> PatientPhones { get; set; }
        public virtual DbSet<PatientProblem> PatientProblems { get; set; }
        public virtual DbSet<PatientRelativeProblem> PatientRelativeProblems { get; set; }
        public virtual DbSet<PersonIdentifierType> PersonIdentifierTypes { get; set; }
        public virtual DbSet<PhoneType> PhoneTypes { get; set; }
        public virtual DbSet<Prescription> Prescriptions { get; set; }
        public virtual DbSet<Problem> Problems { get; set; }
        public virtual DbSet<RelationType> RelationTypes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Visit> Visits { get; set; }
    }
}
