//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novo.Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientNote
    {
        public int Id { get; set; }
        public int PatientId { get; set; }
        public Nullable<int> VisitId { get; set; }
        public int MedicalProviderId { get; set; }
        public System.DateTime NotesDateTime { get; set; }
        public string NotesText { get; set; }
    
        public virtual Visit Visit { get; set; }
    }
}
