//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novo.Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.PatientAddresses = new HashSet<PatientAddress>();
            this.PatientAllergies = new HashSet<PatientAllergy>();
            this.PatientEmails = new HashSet<PatientEmail>();
            this.PatientMedications = new HashSet<PatientMedication>();
            this.PatientPersonIdentifiers = new HashSet<PatientPersonIdentifier>();
            this.PatientPhones = new HashSet<PatientPhone>();
            this.PatientProblems = new HashSet<PatientProblem>();
            this.PatientRelativeProblems = new HashSet<PatientRelativeProblem>();
            this.Prescriptions = new HashSet<Prescription>();
            this.Visits = new HashSet<Visit>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> DateOfDeath { get; set; }
        public Nullable<int> MaritalStatusId { get; set; }
        public Nullable<int> PrimaryCareProviderId { get; set; }
        public int GenderId { get; set; }
    
        public virtual MaritialStatu MaritialStatu { get; set; }
        public virtual MedicalProvider MedicalProvider { get; set; }
        public virtual ICollection<PatientAddress> PatientAddresses { get; set; }
        public virtual ICollection<PatientAllergy> PatientAllergies { get; set; }
        public virtual ICollection<PatientEmail> PatientEmails { get; set; }
        public virtual ICollection<PatientMedication> PatientMedications { get; set; }
        public virtual ICollection<PatientPersonIdentifier> PatientPersonIdentifiers { get; set; }
        public virtual ICollection<PatientPhone> PatientPhones { get; set; }
        public virtual ICollection<PatientProblem> PatientProblems { get; set; }
        public virtual ICollection<PatientRelativeProblem> PatientRelativeProblems { get; set; }
        public virtual ICollection<Prescription> Prescriptions { get; set; }
        public virtual ICollection<Visit> Visits { get; set; }
        public virtual Gender Gender { get; set; }
    }
}
