//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novo.Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientEmail
    {
        public int Id { get; set; }
        public int PatientId { get; set; }
        public string Number { get; set; }
        public int EmailTypeId { get; set; }
    
        public virtual EmailType EmailType { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
