//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novo.Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneType
    {
        public PhoneType()
        {
            this.MedicalProviderPhones = new HashSet<MedicalProviderPhone>();
            this.PatientPhones = new HashSet<PatientPhone>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<MedicalProviderPhone> MedicalProviderPhones { get; set; }
        public virtual ICollection<PatientPhone> PatientPhones { get; set; }
    }
}
