//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novo.Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Problem
    {
        public Problem()
        {
            this.PatientProblems = new HashSet<PatientProblem>();
            this.PatientRelativeProblems = new HashSet<PatientRelativeProblem>();
        }
    
        public int Id { get; set; }
        public string SnoMedCode { get; set; }
        public string ICD9Code { get; set; }
        public string ICD10Code { get; set; }
    
        public virtual ICollection<PatientProblem> PatientProblems { get; set; }
        public virtual ICollection<PatientRelativeProblem> PatientRelativeProblems { get; set; }
    }
}
