//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novo.Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public Visit()
        {
            this.PatientNotes = new HashSet<PatientNote>();
            this.Prescriptions = new HashSet<Prescription>();
        }
    
        public int Id { get; set; }
        public int PatientId { get; set; }
        public int MedicalProviderId { get; set; }
        public int MedicalFacilityId { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public int VisitTypeId { get; set; }
        public Nullable<int> ReferredByMedicalProviderId { get; set; }
        public Nullable<int> ReferredByMedicalFacilityId { get; set; }
    
        public virtual MedicalFacility MedicalFacility { get; set; }
        public virtual MedicalFacility MedicalFacility1 { get; set; }
        public virtual MedicalProvider MedicalProvider { get; set; }
        public virtual MedicalProvider MedicalProvider1 { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual ICollection<PatientNote> PatientNotes { get; set; }
        public virtual ICollection<Prescription> Prescriptions { get; set; }
    }
}
